#!/bin/bash
#Jacob smith Brandeis Auomtation Lab 7/2/2020
#Sets up ROS and runs ROS programs for ROSSERVER Project

#print helper message
echo "Main Command Terminal , will execute the other commands" 
#execute necessary commands for ROSSERVER setup
gnome-terminal \
    --tab -e "bash -c 'echo -ne \"\033]0;Camera\007\" ; cheese; read -n1'" b\                                                          #launch camera
    --tab -e "bash -c   'sleep 2; export TURTLEBOT3_MODEL=burger; roslaunch turtlebot3_gazebo turtlebot3_stage_1.launch;  read -n1'" \ #launch rosluanch
    --tab -e "bash -c 'echo -ne \"\033]0;Robot Commander\007\" ; sleep 1 ; python keys_to_twist.py ; read -n1'"  \                     #launch ROS programs
    --tab -e "bash -c 'echo -ne \"\033]0;Key Publisher\007\" ; sleep 3; python key_publisher.py ; read -n1'" 1>/dev/null 

#close terminal windows after X  seconds
sleep 20
#close gazebo
pkill gzserver 
pkill gzclient
#close terminals
pkill gnome-terminal-