#!/bin/bash
#Jacob smith COSI 119A 9/9/2019 Roomba
#Launches terminal windows and scripts for Roomba assignment
#Modoifed from 4.1Script
#links in readme

#launch webcam program
gnome-terminal --geometry 73x31+0+0 -- /bin/sh -c 'cheese'

#launch roscore in other terminal and wait for it to start up
gnome-terminal --geometry 73x31+200+0 -- /bin/sh -c 'roscore'
sleep 2
#set Model of Turtlebot gazebo, launch gazbo, and wait
gnome-terminal --geometry 73x31+400+0 -- /bin/sh -c 'export TURTLEBOT3_MODEL="burger";roslaunch turtlebot3_gazebo turtlebot3_stage_1.launch'
sleep 4
#loop through every python file in program
#give file permissions and run python file
gnome-terminal --geometry 73x31+600+0 -- /bin/sh -c 'chmod +x roomba.py;python key_publisher.py'

#loop through every python file in program
#give file permissions and run python file6
gnome-terminal --geometry 73x31+800+0 -- /bin/sh -c 'chmod +x roomba.py; python keys_to_twist.py'

#close terminal windows after X  seconds
sleep 60
#close gazebo
pkill gzserver 
pkill gzclient
#close cheese
pkill cheese
#close terminals
pkill gnome-terminal-